[package]
name = "dashboard"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
iced = { version = "0.12", features = ["lazy", "image", "svg"] }
rust-ini = "0.18"

[dev-dependencies]
tempfile = "3"
